version: "3"

services:
  bootcampserver1:
    image: bootserverimage:latest

  bootcampserver2:
    build: ./Server
    image: bootserverimage:latest

  haproxy:
    image:  haproxy:latest
    ports:
      - 8080:80
    depends_on:
      - bootcampserver1
      - bootcampserver2