version: "3"

services:
  bootcampserver1:
    build: ./Server
    image: bootserverimage

  bootcampserver2:
    build: ./Server
    image: bootserverimage

  bootcamphaproxy:
    build: ./HaProxy
    image: haproxy
    ports:
      - 8080:80
    depends_on:
      - bootcampserver1
      - bootcampserver2