version: "3"

services:
  bootcampserver1:
    image: bootserverimage:latest

  bootcampserver2:
    build: ./Server
    image: bootserverimage:latest

  elasticSearch:
    image: elastic/elasticsearch:6.8.3
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200

  haproxy:
    image:  haproxy:latest
    ports:
      - 80:80
    depends_on:
      - bootcampserver1
      - bootcampserver2
      - elasticSearch