CREATE TABLE ACCOUNTS (
    id INT(6) NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    indexName VARCHAR(255) NOT NULL UNIQUE,
    token VARCHAR(33) NOT NULL UNIQUE,
    PRIMARY KEY(id)
);